[2024-10-30T20:10:00.430+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-30T20:10:00.437+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.json_to_csv_review_data manual__2024-10-30T19:46:39.259683+00:00 [queued]>
[2024-10-30T20:10:00.441+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.json_to_csv_review_data manual__2024-10-30T19:46:39.259683+00:00 [queued]>
[2024-10-30T20:10:00.441+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-30T20:10:00.446+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): json_to_csv_review_data> on 2024-10-30 19:46:39.259683+00:00
[2024-10-30T20:10:00.450+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'json_to_csv_review_data', 'manual__2024-10-30T19:46:39.259683+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpifvzo37_']
[2024-10-30T20:10:00.450+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=200) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-30T20:10:00.453+0000] {standard_task_runner.py:105} INFO - Job 101: Subtask json_to_csv_review_data
[2024-10-30T20:10:00.453+0000] {standard_task_runner.py:72} INFO - Started process 202 to run task
[2024-10-30T20:10:00.499+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.json_to_csv_review_data manual__2024-10-30T19:46:39.259683+00:00 [running]> on host 6bca134bba56
[2024-10-30T20:10:00.553+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='json_to_csv_review_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-30T19:46:39.259683+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-30T19:46:39.259683+00:00'
[2024-10-30T20:10:00.555+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-01T18:29:09.887+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-01T18:29:09.908+0000] {taskinstance.py:2602} INFO - Dependencies not met for <TaskInstance: data_pipeline.json_to_csv_review_data manual__2024-10-30T19:46:39.259683+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2024-11-01T18:29:09.926+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
[2024-11-01T18:29:09.931+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-01T18:29:09.949+0000] {taskinstance.py:2602} INFO - Dependencies not met for <TaskInstance: data_pipeline.json_to_csv_review_data manual__2024-10-30T19:46:39.259683+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2024-11-01T18:29:09.972+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
