[2024-10-30T20:35:04.549+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-30T20:35:04.554+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.json_to_csv_review_data manual__2024-10-30T20:23:22.768605+00:00 [queued]>
[2024-10-30T20:35:04.558+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.json_to_csv_review_data manual__2024-10-30T20:23:22.768605+00:00 [queued]>
[2024-10-30T20:35:04.558+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-30T20:35:04.562+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): json_to_csv_review_data> on 2024-10-30 20:23:22.768605+00:00
[2024-10-30T20:35:04.564+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=100) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-30T20:35:04.565+0000] {standard_task_runner.py:72} INFO - Started process 102 to run task
[2024-10-30T20:35:04.565+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'json_to_csv_review_data', 'manual__2024-10-30T20:23:22.768605+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmp583w6bpe']
[2024-10-30T20:35:04.566+0000] {standard_task_runner.py:105} INFO - Job 130: Subtask json_to_csv_review_data
[2024-10-30T20:35:04.581+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.json_to_csv_review_data manual__2024-10-30T20:23:22.768605+00:00 [running]> on host 6bca134bba56
[2024-10-30T20:35:04.607+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='json_to_csv_review_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-30T20:23:22.768605+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-30T20:23:22.768605+00:00'
[2024-10-30T20:35:04.607+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-01T18:29:09.995+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-01T18:29:10.015+0000] {taskinstance.py:2602} INFO - Dependencies not met for <TaskInstance: data_pipeline.json_to_csv_review_data manual__2024-10-30T20:23:22.768605+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2024-11-01T18:29:10.021+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
[2024-11-01T18:29:10.116+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-01T18:29:10.127+0000] {taskinstance.py:2602} INFO - Dependencies not met for <TaskInstance: data_pipeline.json_to_csv_review_data manual__2024-10-30T20:23:22.768605+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2024-11-01T18:29:10.132+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
