[2024-11-03T17:52:31.437+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-03T17:52:31.444+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.createtablemetadata manual__2024-11-03T17:52:14.946080+00:00 [queued]>
[2024-11-03T17:52:31.447+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.createtablemetadata manual__2024-11-03T17:52:14.946080+00:00 [queued]>
[2024-11-03T17:52:31.447+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2024-11-03T17:52:31.453+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): createtablemetadata> on 2024-11-03 17:52:14.946080+00:00
[2024-11-03T17:52:31.461+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=282) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-03T17:52:31.462+0000] {standard_task_runner.py:72} INFO - Started process 292 to run task
[2024-11-03T17:52:31.461+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'createtablemetadata', 'manual__2024-11-03T17:52:14.946080+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpe6tvt4w6']
[2024-11-03T17:52:31.464+0000] {standard_task_runner.py:105} INFO - Job 110: Subtask createtablemetadata
[2024-11-03T17:52:31.497+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.createtablemetadata manual__2024-11-03T17:52:14.946080+00:00 [running]> on host 9ab0960d13ae
[2024-11-03T17:52:31.531+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='createtablemetadata' AIRFLOW_CTX_EXECUTION_DATE='2024-11-03T17:52:14.946080+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-03T17:52:14.946080+00:00'
[2024-11-03T17:52:31.532+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-03T17:52:32.541+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-03T17:52:32.558+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-03T17:52:32.559+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=createtablemetadata, run_id=manual__2024-11-03T17:52:14.946080+00:00, execution_date=20241103T175214, start_date=20241103T175231, end_date=20241103T175232
[2024-11-03T17:52:32.604+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-03T17:52:32.617+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-03T17:52:32.617+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
