[2024-10-30T19:08:33.376+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-30T19:08:33.383+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.create_table_meta_data manual__2024-10-30T19:08:31.851885+00:00 [queued]>
[2024-10-30T19:08:33.387+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.create_table_meta_data manual__2024-10-30T19:08:31.851885+00:00 [queued]>
[2024-10-30T19:08:33.387+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-30T19:08:33.393+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): create_table_meta_data> on 2024-10-30 19:08:31.851885+00:00
[2024-10-30T19:08:33.396+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=161) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-30T19:08:33.396+0000] {standard_task_runner.py:72} INFO - Started process 173 to run task
[2024-10-30T19:08:33.397+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'create_table_meta_data', 'manual__2024-10-30T19:08:31.851885+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmptyeta6ft']
[2024-10-30T19:08:33.398+0000] {standard_task_runner.py:105} INFO - Job 76: Subtask create_table_meta_data
[2024-10-30T19:08:33.420+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.create_table_meta_data manual__2024-10-30T19:08:31.851885+00:00 [running]> on host 6bca134bba56
[2024-10-30T19:08:33.452+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='create_table_meta_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-30T19:08:31.851885+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-30T19:08:31.851885+00:00'
[2024-10-30T19:08:33.453+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-30T19:08:34.383+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-30T19:08:34.389+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-30T19:08:34.390+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=create_table_meta_data, run_id=manual__2024-10-30T19:08:31.851885+00:00, execution_date=20241030T190831, start_date=20241030T190833, end_date=20241030T190834
[2024-10-30T19:08:34.427+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-30T19:08:34.435+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-30T19:08:34.436+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
