[2024-11-03T17:45:51.891+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-03T17:45:51.898+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.transfer_task_review manual__2024-11-03T17:44:50.172889+00:00 [queued]>
[2024-11-03T17:45:51.902+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.transfer_task_review manual__2024-11-03T17:44:50.172889+00:00 [queued]>
[2024-11-03T17:45:51.902+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2024-11-03T17:45:51.906+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): transfer_task_review> on 2024-11-03 17:44:50.172889+00:00
[2024-11-03T17:45:51.909+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=128) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-03T17:45:51.910+0000] {standard_task_runner.py:72} INFO - Started process 132 to run task
[2024-11-03T17:45:51.910+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'transfer_task_review', 'manual__2024-11-03T17:44:50.172889+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmp1msmpqts']
[2024-11-03T17:45:51.911+0000] {standard_task_runner.py:105} INFO - Job 93: Subtask transfer_task_review
[2024-11-03T17:45:51.928+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.transfer_task_review manual__2024-11-03T17:44:50.172889+00:00 [running]> on host 9ab0960d13ae
[2024-11-03T17:45:51.952+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='transfer_task_review' AIRFLOW_CTX_EXECUTION_DATE='2024-11-03T17:44:50.172889+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-03T17:44:50.172889+00:00'
[2024-11-03T17:45:51.953+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-03T17:46:04.960+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-03T17:46:04.977+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-03T17:46:04.978+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=transfer_task_review, run_id=manual__2024-11-03T17:44:50.172889+00:00, execution_date=20241103T174450, start_date=20241103T174551, end_date=20241103T174604
[2024-11-03T17:46:04.997+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-03T17:46:05.009+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-03T17:46:05.010+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
