[2024-11-01T19:30:38.297+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-01T19:30:38.305+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.create_table_user_review manual__2024-11-01T19:30:37.041421+00:00 [queued]>
[2024-11-01T19:30:38.310+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.create_table_user_review manual__2024-11-01T19:30:37.041421+00:00 [queued]>
[2024-11-01T19:30:38.312+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-11-01T19:30:38.320+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): create_table_user_review> on 2024-11-01 19:30:37.041421+00:00
[2024-11-01T19:30:38.324+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=84) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-01T19:30:38.328+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'create_table_user_review', 'manual__2024-11-01T19:30:37.041421+00:00', '--job-id', '198', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmp4_2mzosx']
[2024-11-01T19:30:38.335+0000] {standard_task_runner.py:105} INFO - Job 198: Subtask create_table_user_review
[2024-11-01T19:30:38.333+0000] {standard_task_runner.py:72} INFO - Started process 95 to run task
[2024-11-01T19:30:38.386+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.create_table_user_review manual__2024-11-01T19:30:37.041421+00:00 [running]> on host 6bca134bba56
[2024-11-01T19:30:38.443+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='create_table_user_review' AIRFLOW_CTX_EXECUTION_DATE='2024-11-01T19:30:37.041421+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-01T19:30:37.041421+00:00'
[2024-11-01T19:30:38.444+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-01T19:30:39.553+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-01T19:30:39.573+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-01T19:30:39.574+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=create_table_user_review, run_id=manual__2024-11-01T19:30:37.041421+00:00, execution_date=20241101T193037, start_date=20241101T193038, end_date=20241101T193039
[2024-11-01T19:30:39.609+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-01T19:30:39.619+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-01T19:30:39.620+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
