[2024-11-03T04:45:06.234+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-03T04:45:06.247+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.create_table_meta_data manual__2024-11-03T04:45:03.556640+00:00 [queued]>
[2024-11-03T04:45:06.250+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.create_table_meta_data manual__2024-11-03T04:45:03.556640+00:00 [queued]>
[2024-11-03T04:45:06.250+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-03T04:45:06.257+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): create_table_meta_data> on 2024-11-03 04:45:03.556640+00:00
[2024-11-03T04:45:06.260+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=84) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-03T04:45:06.261+0000] {standard_task_runner.py:72} INFO - Started process 94 to run task
[2024-11-03T04:45:06.262+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'create_table_meta_data', 'manual__2024-11-03T04:45:03.556640+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmprubjydua']
[2024-11-03T04:45:06.264+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask create_table_meta_data
[2024-11-03T04:45:06.300+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.create_table_meta_data manual__2024-11-03T04:45:03.556640+00:00 [running]> on host 0544538d00ef
[2024-11-03T04:45:06.335+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='create_table_meta_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-03T04:45:03.556640+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-03T04:45:03.556640+00:00'
[2024-11-03T04:45:06.336+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-03T04:45:07.525+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-03T04:45:07.531+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-03T04:45:07.531+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=create_table_meta_data, run_id=manual__2024-11-03T04:45:03.556640+00:00, execution_date=20241103T044503, start_date=20241103T044506, end_date=20241103T044507
[2024-11-03T04:45:07.558+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-03T04:45:07.570+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-03T04:45:07.571+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
