[2024-10-30T22:05:27.930+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-30T22:05:27.942+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.json_to_csv_review_data manual__2024-10-30T21:04:39.068508+00:00 [queued]>
[2024-10-30T22:05:27.949+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.json_to_csv_review_data manual__2024-10-30T21:04:39.068508+00:00 [queued]>
[2024-10-30T22:05:27.949+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-30T22:05:27.956+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): json_to_csv_review_data> on 2024-10-30 21:04:39.068508+00:00
[2024-10-30T22:05:27.960+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=382) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-30T22:05:27.961+0000] {standard_task_runner.py:72} INFO - Started process 386 to run task
[2024-10-30T22:05:27.961+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'json_to_csv_review_data', 'manual__2024-10-30T21:04:39.068508+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpejm1v3_f']
[2024-10-30T22:05:27.963+0000] {standard_task_runner.py:105} INFO - Job 142: Subtask json_to_csv_review_data
[2024-10-30T22:05:27.984+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.json_to_csv_review_data manual__2024-10-30T21:04:39.068508+00:00 [running]> on host 6bca134bba56
[2024-10-30T22:05:28.021+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='json_to_csv_review_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-30T21:04:39.068508+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-30T21:04:39.068508+00:00'
[2024-10-30T22:05:28.022+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-30T22:10:03.239+0000] {job.py:229} INFO - Heartbeat recovered after 250.07 seconds
[2024-11-01T18:29:11.018+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-01T18:29:11.022+0000] {taskinstance.py:2602} INFO - Dependencies not met for <TaskInstance: data_pipeline.json_to_csv_review_data manual__2024-10-30T21:04:39.068508+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2024-11-01T18:29:11.024+0000] {taskinstance.py:2602} INFO - Dependencies not met for <TaskInstance: data_pipeline.json_to_csv_review_data manual__2024-10-30T21:04:39.068508+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2024-11-01T18:29:11.025+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
