[2024-10-30T19:08:33.354+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-30T19:08:33.360+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.create_table_user_review manual__2024-10-30T19:08:31.851885+00:00 [queued]>
[2024-10-30T19:08:33.365+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.create_table_user_review manual__2024-10-30T19:08:31.851885+00:00 [queued]>
[2024-10-30T19:08:33.365+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-30T19:08:33.371+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): create_table_user_review> on 2024-10-30 19:08:31.851885+00:00
[2024-10-30T19:08:33.375+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=162) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-30T19:08:33.376+0000] {standard_task_runner.py:72} INFO - Started process 169 to run task
[2024-10-30T19:08:33.376+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'create_table_user_review', 'manual__2024-10-30T19:08:31.851885+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmp34rgszr5']
[2024-10-30T19:08:33.377+0000] {standard_task_runner.py:105} INFO - Job 74: Subtask create_table_user_review
[2024-10-30T19:08:33.400+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.create_table_user_review manual__2024-10-30T19:08:31.851885+00:00 [running]> on host 6bca134bba56
[2024-10-30T19:08:33.436+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='create_table_user_review' AIRFLOW_CTX_EXECUTION_DATE='2024-10-30T19:08:31.851885+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-30T19:08:31.851885+00:00'
[2024-10-30T19:08:33.437+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-30T19:08:34.670+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-30T19:08:34.687+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-30T19:08:34.688+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=create_table_user_review, run_id=manual__2024-10-30T19:08:31.851885+00:00, execution_date=20241030T190831, start_date=20241030T190833, end_date=20241030T190834
[2024-10-30T19:08:34.727+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-30T19:08:34.738+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-30T19:08:34.739+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
