[2024-11-03T16:43:39.697+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-03T16:43:39.705+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.clean_temp_task1 manual__2024-11-03T16:43:38.992473+00:00 [queued]>
[2024-11-03T16:43:39.708+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.clean_temp_task1 manual__2024-11-03T16:43:38.992473+00:00 [queued]>
[2024-11-03T16:43:39.708+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-03T16:43:39.713+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): clean_temp_task1> on 2024-11-03 16:43:38.992473+00:00
[2024-11-03T16:43:39.716+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=254) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-03T16:43:39.716+0000] {standard_task_runner.py:72} INFO - Started process 260 to run task
[2024-11-03T16:43:39.717+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'clean_temp_task1', 'manual__2024-11-03T16:43:38.992473+00:00', '--job-id', '164', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpl7yhbu96']
[2024-11-03T16:43:39.718+0000] {standard_task_runner.py:105} INFO - Job 164: Subtask clean_temp_task1
[2024-11-03T16:43:39.735+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.clean_temp_task1 manual__2024-11-03T16:43:38.992473+00:00 [running]> on host 5acfa859d16b
[2024-11-03T16:43:39.763+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='clean_temp_task1' AIRFLOW_CTX_EXECUTION_DATE='2024-11-03T16:43:38.992473+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-03T16:43:38.992473+00:00'
[2024-11-03T16:43:39.764+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-03T16:43:39.770+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-03T16:43:39.773+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-03T16:43:39.774+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=clean_temp_task1, run_id=manual__2024-11-03T16:43:38.992473+00:00, execution_date=20241103T164338, start_date=20241103T164339, end_date=20241103T164339
[2024-11-03T16:43:39.816+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-03T16:43:39.825+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-03T16:43:39.825+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
